/*---------------------------------------------------------------------------
							Item Defines
			Split into individual file for ease of access
---------------------------------------------------------------------------*/		
// ["MISSION CLASS", WEIGHT, ["REAL GAME CLASSNAME", "MISSION ITEM TITLE", PRICEBUY], "LICENSE(NONE IF NO LICENSE)", "SCRIPT IT RUNS", ["VIRTUAL TYPE"], STORAGESPACE]
AM_Items = [
	// ACE Medical Equipment
	["ACE_atropine", .5, ["Land_Suitcase_F", "Atropin Injector", 10], "ems_lic", "nouse.sqf", ["I_ITEM"],0,"ico_default.paa"],
	["ACE_fieldDressing", .5, ["Land_Suitcase_F", "Field Dressing", 10], "ems_lic", "nouse.sqf", ["I_ITEM"],0,"ico_default.paa"],
	["ACE_elasticBandage", .5, ["Land_Suitcase_F", "Elastic Bandage", 10], "none", "nouse.sqf", ["I_ITEM"],0,"ico_default.paa"],
	["ACE_quikclot", .5, ["Land_Suitcase_F", "Basic Field Dressing", 10], "ems_lic", "nouse.sqf", ["I_ITEM"],0,"ico_default.paa"],
	["ACE_bloodIV", .5, ["Land_Suitcase_F", "Blood IV (1000ml)", 10], "ems_lic", "nouse.sqf", ["I_ITEM"],0,"ico_default.paa"],
	["ACE_epinephrine", .5, ["Land_Suitcase_F", "Epinephrine Auto-Injector", 10], "ems_lic", "nouse.sqf", ["I_ITEM"],0,"ico_default.paa"],
	["ACE_morphine", .5, ["Land_Suitcase_F", "Morphine Auto-Injector", 10], "ems_lic", "nouse.sqf", ["I_ITEM"],0,"ico_default.paa"],
	["ACE_packingBandage", .5, ["Land_Suitcase_F", "Packing Bandage", 10], "none", "nouse.sqf", ["I_ITEM"],0,"ico_default.paa"],
	["ACE_personalAidKit", .5, ["Land_Suitcase_F", "Personal Aid Kit", 10], "none", "nouse.sqf", ["I_ITEM"],0,"ico_default.paa"],
	["ACE_plasmaIV", .5, ["Land_Suitcase_F", "Plasma IV (1000ml)", 10], "ems_lic", "nouse.sqf", ["I_ITEM"],0,"ico_default.paa"],
	["ACE_salineIV", .5, ["Land_Suitcase_F", "Saline IV (1000ml)", 10], "ems_lic", "nouse.sqf", ["I_ITEM"],0,"ico_default.paa"],
	["ACE_surgicalKit", .5, ["Land_Suitcase_F", "Surgical Kit", 10], "ems_lic", "nouse.sqf", ["I_ITEM"],0,"ico_default.paa"],
	["ACE_tourniquet", .5, ["Land_Suitcase_F", "Tourniquet", 10], "ems_lic", "nouse.sqf", ["I_ITEM"],0,"ico_default.paa"],
    //Test Items
	["testitem1", 1, ["Land_Suitcase_F", "Test Item", 6], "none", "nouse.sqf", ["ITEM"],0,"ico_default.paa"],
	["testitem2", 1, ["Land_Suitcase_F", "Test Item 2", 7], "none", "nouse.sqf", ["ITEM"],0,"ico_default.paa"],
	["testitem3", 1, ["Land_Suitcase_F", "Test Item 3", 8], "none", "nouse.sqf", ["ITEM"],0,"ico_default.paa"],

    //Items
    ["handcuffs",1,["AM_Cuffs","Handcuff",56], "none", "nouse_binded.sqf", ["ITEM"], 0,"ico_default.paa"],
    ["rope",1,["Land_Suitcase_F","Bounding Rope",25], "none", "nouse_binded.sqf", ["ITEM"], 0,"ico_default.paa"],
    ["headbag",1,["Land_Suitcase_F","Head Bag",80], "none", "nouse_binded.sqf", ["ITEM"], 0,"ico_default.paa"],

	["repairkit", 1, ["Land_Suitcase_F", "Repair Kit", 30], "none", "nouse.sqf", ["ITEM"],0,"ico_default.paa"],
	["carjack", 1, ["Land_Suitcase_F", "Vehicle Jack", 40], "none", "nouse.sqf", ["ITEM"],0,"ico_default.paa"],

	["cash", 0, ["Land_Money_F", "Cash", 1], "none", "nouse.sqf", ["ITEM"],0,"ico_cash.paa"],
	["Binocular",1, ["Binocular","Binocular", 40], "none", "nouse.sqf", ["ITEM"],0,"ico_default.paa"],
	["ItemRadio",1, ["ItemRadio","ItemRadio", 75], "none", "nouse.sqf", ["ITEM"],0,"ico_default.paa"],
	["ItemCompass",1, ["ItemCompass","ItemCompass", 25], "none", "nouse.sqf", ["ITEM"],0,"ico_default.paa"],
	["ItemGPS",1, ["ItemGPS","ItemGPS", 45], "none", "nouse.sqf", ["ITEM"],0,"ico_default.paa"],
	["ItemMap",1, ["ItemMap","ItemMap", 5], "none", "nouse.sqf", ["ITEM"],0,"ico_default.paa"],
	["FirstAidKit",1, ["FirstAidKit","FirstAidKit", 40], "none", "nouse.sqf", ["ITEM"],0,"ico_default.paa"],
	["NVGoggles",1, ["NVGoggles","NV Goggles (Brown)", 100], "none", "nouse.sqf", ["ITEM"],0,"ico_default.paa"],
	["NVGoggles_OPFOR",1, ["NVGoggles_OPFOR","NV Goggles (Black)", 100], "none", "nouse.sqf", ["ITEM"],0,"ico_default.paa"],
	["NVGoggles_INDEP",1, ["NVGoggles_INDEP","NV Goggles (Green)", 100], "none", "nouse.sqf", ["ITEM"],0,"ico_default.paa"],
	["Rangefinder",1, ["Rangefinder","Rangefinder", 60], "none", "nouse.sqf", ["ITEM"],0,"ico_default.paa"],
	["pmc_earpiece",1, ["pmc_earpiece","Ear-Piece", 60], "none", "nouse.sqf", ["ITEM"],0,"ico_default.paa"],
	["Chemlight_red",1, ["Chemlight_red","Chemlight_red", 10], "none", "nouse.sqf", ["MAG"],0,"ico_default.paa"],
	["Chemlight_green",1, ["Chemlight_green","Chemlight_green", 10], "none", "nouse.sqf", ["MAG"],0,"ico_default.paa"],
	["Chemlight_bule",1, ["Chemlight_bule","Chemlight_bule", 10], "none", "nouse.sqf", ["MAG"],0,"ico_default.paa"],
	["Chemlight_yellow",1, ["Chemlight_yellow","Chemlight_yellow", 10], "none", "nouse.sqf", ["MAG"],0,"ico_default.paa"],
	["tf_anprc152",1, ["tf_anprc152","TaskForce Radio Bag", 75], "none", "nouse.sqf", ["ITEM"],0,"ico_default.paa"],
	["tf_anprc155_coyote",1, ["tf_anprc155_coyote","TaskForce Coyote Bag", 75], "none", "nouse.sqf", ["ITEM"],0,"ico_default.paa"],
	    //=================\\
	   //-- PLANTATION ITEMS\\
	  //---1: PLANTATION IN -\\
	 //---2: PLANTATION OUT --\\
	//=========================\\
	["tabacco_seeds", 1, ["Land_Suitcase_F", "tobacco Seeds", 100], "none", AM_CodePack_ItemScripts+"f_plantseed.sqf", ["ITEM"],0,"ico_default.paa"],
	["tabacco_leaves",3, ["Land_Suitcase_F", "tobacco Leaves", 360], "none",  "nouse.sqf", ["ITEM"],0,"ico_default.paa"],
	["tabacco", 3, ["Land_Suitcase_F","tobacco",400], "none","nouse.sqf",["ITEM"],0,"ico_default.paa"],
	//Mining
	["Cement", 20, ["Land_Suitcase_F", "Cement", 150], "none", "nouse.sqf", ["ITEM"],0,"ico_default.paa"],
	["Copper_In", 10, ["Land_Suitcase_F", "Copper", 200], "none", "nouse.sqf", ["ITEM"],0,"ico_default.paa"],
	["Iron_In", 10, ["Land_Suitcase_F", "Iron Ingots", 460], "none", "nouse.sqf", ["ITEM"],0,"ico_default.paa"],
	["Gold_In", 10, ["Land_Suitcase_F", "Gold Ingots", 800], "none", "nouse.sqf", ["ITEM"],0,"ico_default.paa"],
	["E_Stone", 5, ["Land_Suitcase_F", "Emerald Stone", 1000], "none", "nouse.sqf", ["ITEM"],0,"ico_default.paa"],
	["D_Stone", 5, ["Land_Suitcase_F", "Diamond Stone", 1200], "none", "nouse.sqf", ["ITEM"],0,"ico_default.paa"],
	["R_Stone", 5, ["Land_Suitcase_F", "Ruby Stone", 1300], "none", "nouse.sqf", ["ITEM"],0,"ico_default.paa"],
	//Fishing
	["Oil_P", 15, ["Land_Suitcase_F", "3-liters of Gasoline", 5000], "none", "nouse.sqf", ["ITEM"],0,"ico_default.paa"],

	//=======================================================================================================\\
	//Water
	["Water", 5, ["Land_Suitcase_F", "Water", 30], "none", "use.sqf", ["ITEM"],0,"ico_default.paa"],
	["Soda", 5, ["Land_Suitcase_F", "Coca Loca", 30], "none", "use.sqf", ["ITEM"],0,"ico_default.paa"],
	//Food
	["hamburger", 1, ["Land_Suitcase_F", "Hamburger", 12], "none", "use.sqf", ["ITEM"],0,"ico_default.paa"],
	["french_fries", 1, ["Land_Suitcase_F", "French Fries", 6], "none", "use.sqf", ["ITEM"],0,"ico_default.paa"],
	["Eel_M", 15, ["Land_Suitcase_F", "Eel Meat", 700], "none", "use.sqf", ["ITEM"],0,"ico_default.paa"],
	["CatFish_M", 15, ["Land_Suitcase_F", "CatFish Meat", 400], "none", "use.sqf", ["ITEM"],0,"ico_default.paa"],
	["KoiFish_M", 15, ["Land_Suitcase_F", "KoiFish Meat", 200], "none", "use.sqf", ["ITEM"],0,"ico_default.paa"],
	["Shark_M", 30, ["Land_Suitcase_F", "Shark Meat", 2000], "none", "use.sqf", ["ITEM"],0,"ico_default.paa"],
	["Whale_S", 5, ["Land_Suitcase_F", "Whale Meat", 3000], "none", "use.sqf", ["ITEM"],0,"ico_default.paa"],
	["Crab_L", 5, ["Land_Suitcase_F", "Crab Legs", 900], "none", "use.sqf", ["ITEM"],0,"ico_default.paa"],

	//Fishing
	["Fishingpole", 1, ["Land_Suitcase_F", "Fishing Pole (OffShore)", 65], "none", "scripts\near.sqf", ["ITEM"],0,"ico_default.paa"],
	["FishingpoleSea", 1, ["Land_Suitcase_F", "Fishing Pole (Sea)", 85], "none", "scripts\near.sqf", ["ITEM"],0,"ico_default.paa"],
	["Crab", 5, ["Land_Suitcase_F", "(Off-Shore Fish) Crab", 20], "none", "nouse.sqf", ["ITEM"],0,"ico_default.paa"],
	["Eel", 15, ["Land_Suitcase_F", "(Off-Shore Fish) Eel", 18], "none", "nouse.sqf", ["ITEM"],0,"ico_default.paa"],
	["CatFish", 15, ["Land_Suitcase_F", "(Off-Shore Fish) CatFish", 27], "none", "nouse.sqf", ["ITEM"],0,"ico_default.paa"],
	["KoiFish", 15, ["Land_Suitcase_F", "(Off-Shore Fish) KoiFish", 24], "none", "nouse.sqf", ["ITEM"],0,"ico_default.paa"],
	["Shark", 100, ["Land_Suitcase_F", "(Sea-Fish) Shark", 60], "none", "nouse.sqf", ["ITEM"],0,"ico_default.paa"],
	["Whale", 300, ["Land_Suitcase_F", "(Sea-Fish) Whale", 120], "none", "nouse.sqf", ["ITEM"],0,"ico_default.paa"],
	["Oil", 100, ["Land_Suitcase_F", "Oil Un-Processed", 50], "none", "nouse.sqf", ["ITEM"],0,"ico_default.paa"],
	["Shoe", 5, ["Land_Suitcase_F", "Shoe", 30], "none", "nouse.sqf", ["ITEM"],0,"ico_default.paa"],

	//Mining
	["Mining_Pick", 1, ["Land_Suitcase_F", "Mining Pick", 5], "none", "scripts\mining.sqf", ["ITEM"],0,"ico_default.paa"],
	["Rocks", 10, ["Land_Suitcase_F", "Stone", 50], "none", "nouse.sqf", ["ITEM"],0,"ico_default.paa"],
	["Coal", 20, ["Land_Suitcase_F", "Coal", 45], "none", "nouse.sqf", ["ITEM"],0,"ico_default.paa"],
	["Copper", 40, ["Land_Suitcase_F", "Copper Ore", 30], "none", "nouse.sqf", ["ITEM"],0,"ico_default.paa"],
	["Iron", 50, ["Land_Suitcase_F", "Iron Ore", 45], "none", "nouse.sqf", ["ITEM"],0,"ico_default.paa"],
	["Gold", 80, ["Land_Suitcase_F", "Gold Ore", 60], "none", "nouse.sqf", ["ITEM"],0,"ico_default.paa"],
	["Emerald", 15, ["Land_Suitcase_F", "Emerald Ore", 65], "none", "nouse.sqf", ["ITEM"],0,"ico_default.paa"],
	["Diamond", 15, ["Land_Suitcase_F", "Diamond Ore", 70], "none", "nouse.sqf", ["ITEM"],0,"ico_default.paa"],
	["Ruby", 10, ["Land_Suitcase_F", "Ruby Ore", 65], "none", "nouse.sqf", ["ITEM"],0,"ico_default.paa"],

	//Police Cars
	["AM_08CrownVic_P_P", 0, ["AM_08CrownVic_P_P", "2011 Ford Crown Victoria (Police Patrol) [REMOVED]", 10], "police_auth", "nouse.sqf", ["CAR"],100,"ico_default.paa"],
	["AM_12Charger_P_P", 0, ["AM_12Charger_P_P", "2012 Dodge Charger (Police Patrol)", 10], "police_auth", "nouse.sqf", ["CAR"],100,"ico_default.paa"],
	["AM_09Tahoe_P_P", 0, ["AM_09Tahoe_P_P", "2009 Chevrolet Tahoe (Police Patrol)", 10], "police_auth", "nouse.sqf", ["CAR"],100,"ico_default.paa"],
	["AM_09Tahoe_U_T", 0, ["AM_09Tahoe_U_T", "2009 Chevrolet Tahoe (Police Slickop)", 10], "police_auth", "nouse.sqf", ["CAR"],100,"ico_default.paa"],
	["AM_15Charger_P_P", 0, ["AM_15Charger_P_P", "2015 Dodge Charger R/T (Police Patrol)", 10], "police_auth", "nouse.sqf", ["CAR"],100,"ico_default.paa"],
	["AM_Ambulance_White", 0, ["AM_Ambulance_White", "Ford F350 Ambulance", 10], "ems_auth", "nouse.sqf", ["CAR"],100,"ico_default.paa"],
	["AM_F350_P_P", 0, ["AM_F350_P_P", "2008 Ford F350 (Police Patrol)", 10], "police_auth", "nouse.sqf", ["CAR"],100,"ico_default.paa"],
	["AM_08Commodore_P_P", 0, ["AM_Commodore_P_P", "2008 Holden Commodore (Highway Patrol)", 10], "police_auth", "nouse.sqf", ["CAR"],100,"ico_default.paa"],
	["AM_14Redline_P_P", 0, ["AM_14Redline_P_P", "2014 Holden Commodore Evoke (Highway Patrol)", 10], "police_auth", "nouse.sqf", ["CAR"],100,"ico_default.paa"],
	//["AM_Explorer_Police", 0, ["AM_Explorer_Police", "2014 Ford Explorer PPV", 25000], "drivers", "nouse.sqf", ["CAR"],200],
	//["AM_2012C_P_P", 0, ["AM_2012C_P_P", "2012 Dodge Charger Patrol", 27000], "drivers", "nouse.sqf", ["CAR"],190],

	
	//Heli
	["B_Heli_Light_01_F", 0, ["B_Heli_Light_01_F", "Hummingbird MH-6", 100000], "none", "nouse.sqf", ["CAR"],300,"ico_default.paa"],

	//Civ Cars
	["AM_LandRover_White", 0, ["AM_LandRover_White", "LandRover (Black)", 28000], "drivers", "nouse.sqf", ["CAR"],120,"ico_default.paa"],
	["AM_LandRover_Silver", 0, ["AM_LandRover_Silver", "LandRover (Silver)", 28000], "drivers", "nouse.sqf", ["CAR"],120,"ico_default.paa"],
	["AM_LandRover_Grey", 0, ["AM_LandRover_Grey", "LandRover (Grey)", 28000], "drivers", "nouse.sqf", ["CAR"],120,"ico_default.paa"],
	["AM_LandRover_Black", 0, ["AM_LandRover_Black", "LandRover (Black)", 28000], "drivers", "nouse.sqf", ["CAR"],120,"ico_default.paa"],
	["AM_LandRover_Red", 0, ["AM_LandRover_Red", "LandRover (Red)", 28000], "drivers", "nouse.sqf", ["CAR"],120,"ico_default.paa"],
	["AM_LandRover_Orange", 0, ["AM_LandRover_Orange", "LandRover (Orange)", 28000], "drivers", "nouse.sqf", ["CAR"],120,"ico_default.paa"],
	["AM_LandRover_Yellow", 0, ["AM_LandRover_Yellow", "LandRover (Yellow)", 28000], "drivers", "nouse.sqf", ["CAR"],120,"ico_default.paa"],
	["AM_LandRover_Green", 0, ["AM_LandRover_Green", "LandRover (Green)", 28000], "drivers", "nouse.sqf", ["CAR"],120,"ico_default.paa"],
	["AM_LandRover_Blue", 0, ["AM_LandRover_Blue", "LandRover (Blue)", 28000], "drivers", "nouse.sqf", ["CAR"],120,"ico_default.paa"],
	["AM_LandRover_Pink", 0, ["AM_LandRover_Pink", "LandRover (Pink)", 28000], "drivers", "nouse.sqf", ["CAR"],120,"ico_default.paa"],
	["AM_LandRover_Purple", 0, ["AM_LandRover_Purple", "LandRover (Purple)", 28000], "drivers", "nouse.sqf", ["CAR"],120,"ico_default.paa"],

	["AM_Q7_White", 0, ["AM_Q7_White", "2011 Audi Q7 (Black)", 28000], "drivers", "nouse.sqf", ["CAR"],90,"ico_default.paa"],
	["AM_Q7_Silver", 0, ["AM_Q7_Silver", "2011 Audi Q7 (Silver)", 28000], "drivers", "nouse.sqf", ["CAR"],90,"ico_default.paa"],
	["AM_Q7_Grey", 0, ["AM_Q7_Grey", "2011 Audi Q7 (Grey)", 28000], "drivers", "nouse.sqf", ["CAR"],90,"ico_default.paa"],
	["AM_Q7_Black", 0, ["AM_Q7_Black", "2011 Audi Q7 (Black)", 28000], "drivers", "nouse.sqf", ["CAR"],90,"ico_default.paa"],
	["AM_Q7_Red", 0, ["AM_Q7_Red", "2011 Audi Q7 (Red)", 28000], "drivers", "nouse.sqf", ["CAR"],90,"ico_default.paa"],
	["AM_Q7_Orange", 0, ["AM_Q7_Orange", "2011 Audi Q7 (Orange)", 28000], "drivers", "nouse.sqf", ["CAR"],90,"ico_default.paa"],
	["AM_Q7_Yellow", 0, ["AM_Q7_Yellow", "2011 Audi Q7 (Yellow)", 28000], "drivers", "nouse.sqf", ["CAR"],90,"ico_default.paa"],
	["AM_Q7_Green", 0, ["AM_Q7_Green", "2011 Audi Q7 (Green)", 28000], "drivers", "nouse.sqf", ["CAR"],90,"ico_default.paa"],
	["AM_Q7_Blue", 0, ["AM_Q7_Blue", "2011 Audi Q7 (Blue)", 28000], "drivers", "nouse.sqf", ["CAR"],90,"ico_default.paa"],
	["AM_Q7_Pink", 0, ["AM_Q7_Pink", "2011 Audi Q7 (Pink)", 28000], "drivers", "nouse.sqf", ["CAR"],90,"ico_default.paa"],
	["AM_Q7_Purple", 0, ["AM_Q7_Purple", "2011 Audi Q7 (Purple)", 28000], "drivers", "nouse.sqf", ["CAR"],90,"ico_default.paa"],

	["AM_X5_White", 0, ["AM_X5_White", "AM X5 White", 18000], "drivers", "nouse.sqf", ["CAR"],70,"ico_default.paa"],
	["AM_X5_Silver", 0, ["AM_X5_Silver", "AM X5 White", 18000], "drivers", "nouse.sqf", ["CAR"],70,"ico_default.paa"],
	["AM_X5_Black", 0, ["AM_X5_Black", "AM X5 Black", 18000], "drivers", "nouse.sqf", ["CAR"],70,"ico_default.paa"],
	["AM_X5_Red", 0, ["AM_X5_Red", "AM X5 Red", 18000], "drivers", "nouse.sqf", ["CAR"],70,"ico_default.paa"],
	["AM_X5_Orange", 0, ["AM_X5_Orange", "AM X5 Orange", 18000], "drivers", "nouse.sqf", ["CAR"],70,"ico_default.paa"],
	["AM_X5_Yellow", 0, ["AM_X5_Yellow", "AM X5 Yellow", 18000], "drivers", "nouse.sqf", ["CAR"],70,"ico_default.paa"],
	["AM_X5_Green", 0, ["AM_X5_Green", "AM X5 Green", 18000], "drivers", "nouse.sqf", ["CAR"],70,"ico_default.paa"],
	["AM_X5_Blue", 0, ["AM_X5_Blue", "AM X5 Blue", 18000], "drivers", "nouse.sqf", ["CAR"],70,"ico_default.paa"],


	["AM_Sexcalade_White", 0, ["AM_Sexcalade_White", "Escalade White", 18000], "drivers", "nouse.sqf", ["CAR"],70,"ico_default.paa"],
	["AM_Sexcalade_Silver", 0, ["AM_Sexcalade_Silver", "Escalade Silver", 18000], "drivers", "nouse.sqf", ["CAR"],70,"ico_default.paa"],
	["AM_Sexcalade_Black", 0, ["AM_Sexcalade_Black", "Escalade Black", 18000], "drivers", "nouse.sqf", ["CAR"],70,"ico_default.paa"],
	["AM_Sexcalade_Red", 0, ["AM_Sexcalade_Red", "Escalade Red", 18000], "drivers", "nouse.sqf", ["CAR"],70,"ico_default.paa"],
	["AM_Sexcalade_Orange", 0, ["AM_Sexcalade_Orange", "Escalade Orange", 18000], "drivers", "nouse.sqf", ["CAR"],70,"ico_default.paa"],
	["AM_Sexcalade_Yellow", 0, ["AM_Sexcalade_Yellow", "Escalade Yellow", 18000], "drivers", "nouse.sqf", ["CAR"],70,"ico_default.paa"],
	["AM_Sexcalade_Green", 0, ["AM_Sexcalade_Green", "Escalade Green", 18000], "drivers", "nouse.sqf", ["CAR"],70,"ico_default.paa"],
	["AM_Sexcalade_Blue", 0, ["AM_Sexcalade_Blue", "Escalade Blue", 18000], "drivers", "nouse.sqf", ["CAR"],70,"ico_default.paa"],
	["AM_Sexcalade_Purple", 0, ["AM_Sexcalade_Purple", "Escalade Purple", 18000], "drivers", "nouse.sqf", ["CAR"],70,"ico_default.paa"],


	["AM_GTR_White", 0, ["AM_GTR_White", "GTR White", 18000], "drivers", "nouse.sqf", ["CAR"],70],
	["AM_GTR_Grey", 0, ["AM_GTR_Grey", "GTR Grey", 18000], "drivers", "nouse.sqf", ["CAR"],70],
	["AM_GTR_Black", 0, ["AM_GTR_Black", "GTR Black", 18000], "drivers", "nouse.sqf", ["CAR"],70],
	["AM_GTR_Red", 0, ["AM_GTR_Red", "GTR Red", 18000], "drivers", "nouse.sqf", ["CAR"],70],
	["AM_GTR_Orange", 0, ["AM_GTR_Orange", "GTR Orange", 18000], "drivers", "nouse.sqf", ["CAR"],70],
	["AM_GTR_Blue", 0, ["AM_GTR_Blue", "GTR Blue", 18000], "drivers", "nouse.sqf", ["CAR"],70],
	["AM_GTR_Green", 0, ["AM_GTR_Green", "GTR Green", 18000], "drivers", "nouse.sqf", ["CAR"],70],

	["AM_15Charger_Black",0,["AM_15Charger_Black", "2015 Dodge Charger (Black)", 70000],"drivers","nouse.sqf",["CAR"],50],
	["AM_15Charger_Red",0,["AM_15Charger_Red", "2015 Dodge Charger (Red)", 70000],"drivers","nouse.sqf",["CAR"],50],
	["AM_15Charger_White",0,["AM_15Charger_White", "2015 Dodge Charger (White)", 70000],"drivers","nouse.sqf",["CAR"],50],
	["AM_15Charger_Green",0,["AM_15Charger_Green", "2015 Dodge Charger (Green)", 70000],"drivers","nouse.sqf",["CAR"],50],


	["AM_12Charger_Black",0,["AM_15Charger_Black", "2015 Dodge Charger (Black)", 70000],"drivers","nouse.sqf",["CAR"],50],
	["AM_12Charger_Red",0,["AM_15Charger_Red", "2015 Dodge Charger (Red)", 70000],"drivers","nouse.sqf",["CAR"],50],
	["AM_12Charger_White",0,["AM_15Charger_White", "2015 Dodge Charger (White)", 70000],"drivers","nouse.sqf",["CAR"],50],
	["AM_12Charger_Green",0,["AM_15Charger_Green", "2015 Dodge Charger (Green)", 70000],"drivers","nouse.sqf",["CAR"],50],

	["AM_Explorer_White", 0, ["AM_Explorer_White", "Ford Explorer (White)", 18000], "drivers", "nouse.sqf", ["CAR"],70],
	["AM_Explorer_Silver", 0, ["AM_Explorer_Silver", "Ford Explorer (Silver)", 18000], "drivers", "nouse.sqf", ["CAR"],70],
	["AM_Explorer_Grey", 0, ["AM_Explorer_Grey", "Ford Explorer (Grey)", 18000], "drivers", "nouse.sqf", ["CAR"],70],
	["AM_Explorer_Black", 0, ["AM_Explorer_Black", "Ford Explorer (Black)", 18000], "drivers", "nouse.sqf", ["CAR"],70],
	["AM_Explorer_Red", 0, ["AM_Explorer_Red", "Ford Explorer (Red)", 18000], "drivers", "nouse.sqf", ["CAR"],70],
	["AM_Explorer_Orange", 0, ["AM_Explorer_Orange", "Ford Explorer (Orange)", 18000], "drivers", "nouse.sqf", ["CAR"],70],
	["AM_Explorer_Yellow", 0, ["AM_Explorer_Yellow", "Ford Explorer (Yellow)", 18000], "drivers", "nouse.sqf", ["CAR"],70],
	["AM_Explorer_Green", 0, ["AM_Explorer_Green", "Ford Explorer (Green)", 18000], "drivers", "nouse.sqf", ["CAR"],70],
	["AM_Explorer_Blue", 0, ["AM_Explorer_Blue", "Ford Explorer (Blue)", 18000], "drivers", "nouse.sqf", ["CAR"],70],
	["AM_Explorer_Pink", 0, ["AM_Explorer_Pink", "Ford Explorer (Pink)", 18000], "drivers", "nouse.sqf", ["CAR"],70],
	["AM_Explorer_Purple", 0, ["AM_Explorer_Purple", "Ford Explorer (Purple)", 18000], "drivers", "nouse.sqf", ["CAR"],70],

	["AM_Trailblazer_White", 0, ["AM_Trailblazer_White", "Chevrolet Trailblazer (White)", 12000], "drivers", "nouse.sqf", ["CAR"],70],
	["AM_Trailblazer_Silver", 0, ["AM_Trailblazer_Silver", "Chevrolet Trailblazer (Silver)", 12000], "drivers", "nouse.sqf", ["CAR"],70],
	["AM_Trailblazer_Grey", 0, ["AM_Trailblazer_Grey", "Chevrolet Trailblazer (Grey)", 12000], "drivers", "nouse.sqf", ["CAR"],70],
	["AM_Trailblazer_Black", 0, ["AM_Trailblazer_Black", "Chevrolet Trailblazer (Black)", 12000], "drivers", "nouse.sqf", ["CAR"],70],
	["AM_Trailblazer_Red", 0, ["AM_Trailblazer_Red", "Chevrolet Trailblazer (Red)", 12000], "drivers", "nouse.sqf", ["CAR"],70],
	["AM_Trailblazer_Yellow", 0, ["AM_Trailblazer_Yellow", "Chevrolet Trailblazer (Yellow)", 12000], "drivers", "nouse.sqf", ["CAR"],70],
	["AM_Trailblazer_Green", 0, ["AM_Trailblazer_Green", "Chevrolet Trailblazer (Green)", 12000], "drivers", "nouse.sqf", ["CAR"],70],
	["AM_Trailblazer_Blue", 0, ["AM_Trailblazer_Blue", "Chevrolet Trailblazer (Blue)", 12000], "drivers", "nouse.sqf", ["CAR"],70],
	["AM_Trailblazer_Pink", 0, ["AM_Trailblazer_Pink", "Chevrolet Trailblazer (Pink)", 12000], "drivers", "nouse.sqf", ["CAR"],70],
	["AM_Trailblazer_Orange", 0, ["AM_Trailblazer_Orange", "Chevrolet Trailblazer (Orange)", 12000], "drivers", "nouse.sqf", ["CAR"],70],

	["AM_Trailblazer_Purple", 0, ["AM_Trailblazer_Purple", "Chevrolet Trailblazer (Purple)", 12000], "drivers", "nouse.sqf", ["CAR"],70],
    
    ["AM_S331_Black", 0, ["ALR_S331_Black","S331 Black", 16000], "drivers", "nouse.sqf", ["CAR"],120],
    ["AM_S331_White", 0, ["ALR_S331_Black","S331 Black", 16000], "drivers", "nouse.sqf", ["CAR"],120],


	["AM_94Civic_White", 0, ["AM_94Civic_White","1994 Honda Civic (White)", 1200], "drivers", "nouse.sqf", ["CAR"],40],
	["AM_94Civic_Black", 0, ["AM_94Civic_Black","1994 Honda Civic (Black)", 1200], "drivers", "nouse.sqf", ["CAR"],40],
	["AM_94Civic_Red", 0, ["AM_94Civic_Red","1994 Honda Civic (Red", 16000], "drivers", "nouse.sqf", ["CAR"],40],
	
	["AM_08Commodore_Black", 0, ["AM_08Commodore_Black","2008 Holden  VE Commodore (Black)", 21500], "drivers", "nouse.sqf", ["CAR"],50],		
	["AM_08Commodore_White", 0, ["AM_08Commodore_White","2008 Holden VE Commodore (White)", 21500], "drivers", "nouse.sqf", ["CAR"],50],		
	["AM_08Commodore_Red", 0, ["AM_08Commodore_Red","2008 Holden VE Commodore (Red)", 21500], "drivers", "nouse.sqf", ["CAR"],50],		
	["AM_08Commodore_Green", 0, ["AM_08Commodore_Green","2008 Holden VE Commodore (Green)", 21500], "drivers", "nouse.sqf", ["CAR"],50],		

	["AM_14Redline_White", 0, ["AM_14Redline_White","2014 Holden VF Commodore Evoke (White)", 32500], "drivers", "nouse.sqf", ["CAR"],50],		
	["AM_14Redline_Red", 0, ["AM_14Redline_Red","2014 Holden VF Commodore Evoke (Red)", 32500], "drivers", "nouse.sqf", ["CAR"],50],		
	["AM_14Redline_Black", 0, ["AM_14Redline_Black","2014 Holden  VF Commodore Evoke (Black)", 32500], "drivers", "nouse.sqf", ["CAR"],50],		
	//Boats
	["B_Lifeboat", 0, ["B_Lifeboat", "Orange Boat", 600], "boat", "nouse.sqf", ["CAR"],50],
	//EMS
	["AM_AmbulancE_White", 0, ["AM_AmbulancE_White","White Ambulance", 10], "ems_lic", "nouse.sqf", ["CAR"],100],
	["ARMSCor_A109_Civ", 0, ["ARMSCor_A109_Civ","A109", 10], "ems_lic", "nouse.sqf", ["CAR"],100],
	["dezkit_b206_rescue", 0, ["dezkit_b206_rescue","Bell 206 Rescue", 10], "ems_lic", "nouse.sqf", ["CAR"],100],

	// Kits
	["police_kits_cadet", 0, ["Land_Suitcase_F", "Police Cadet Kit", 10], "police_auth", AM_CodePack_ItemScripts+"kits.sqf", ["ITEM"],50,"ico_default.paa"],	
	["police_kits_officer", 0, ["Land_Suitcase_F", "Police Officer Kit", 10], "police_auth", AM_CodePack_ItemScripts+"kits.sqf", ["ITEM"],50,"ico_default.paa"],	
	["police_kits_sgt", 0, ["Land_Suitcase_F", "Police Sergeant Kit", 10], "police_auth", AM_CodePack_ItemScripts+"kits.sqf", ["ITEM"],50,"ico_default.paa"],	
	["police_kits_lt", 0, ["Land_Suitcase_F", "Police Lieutenant Kit", 10], "police_auth", AM_CodePack_ItemScripts+"kits.sqf", ["ITEM"],50,"ico_default.paa"],	
	["police_kits_maj", 0, ["Land_Suitcase_F", "Police Major Kit", 10], "police_auth", AM_CodePack_ItemScripts+"kits.sqf", ["ITEM"],50,"ico_default.paa"],	



	//Assault Rifles
	["big_rifle",20, ["srifle_GM6_F","GM6 Lynx", 9700], "rifle_bolt", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
	["hlc_rifle_Bushmaster300",20, ["hlc_rifle_Bushmaster300","Bushmaster 300", 1112], "none", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
	["rifle_ak74",20, ["hlc_rifle_ak74","AK-74 (Assault Rifle)", 1300], "none", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
	["rifle_aks74",20, ["hlc_rifle_aks74","AKS-74 (Assault Rifle)", 1375], "none", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
	["rifle_aks74u",20, ["hlc_rifle_aks74u","AKS-74U (Assault Rifle)", 1390], "none", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
	["rifle_akm",20, ["hlc_rifle_akm","AKM (Assault Rifle)", 1099], "none", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
	["rifle_FAL5061",20, ["hlc_rifle_FAL5061","FN-FAL (Assault Rifle)", 1250], "none", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
	["rifle_g3a3",20, ["hlc_rifle_g3a3","G3A3 (Assault Rifle)", 2750], "none", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
	["rifle_M14",20, ["hlc_rifle_M14","M14 (Assault Rifle)", 1349], "none", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
	["ar10",20, ["RH_ar10","AR-10 (Assault Rifle)", 1165], "none", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
	["m16a1",20, ["RH_m16a1","M16 (Assault Rifle)", 1359], "none", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
	["m16a2",20, ["RH_m16a2","M16A2 (Assault Rifle)", 1400], "none", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
	["m16a3",20, ["RH_m16a3","M16A3 (Assault Rifle)", 1450], "none", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
	["m16a4",20, ["RH_m16a4","M16 Acog (Assault Rifle)", 1500], "none", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
	["m4a6",20, ["RH_m4a6","M4A6 (Assault Rifle)", 1540], "none", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
	["hk416",20, ["RH_hk416","HK-416 (Assault Rifle)", 1420], "none", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
	["M4_moe_b",20, ["RH_M4_moe_b","MAGPUL M4 (Assault Rifle)", 1600], "none", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
	["qdss_nt4",20, ["RH_qdss_nt4","M4 Suppressed (Assault Rifle)", 1700], "none", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
	["rifle_auga3_b",20, ["hlc_rifle_auga3_b","Steyr AUG (Assault Rifle)", 1749], "none", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
    ["muzzle_snds_AUG",20, ["hlc_muzzle_snds_AUG","Muzzled AUG (Assault Rifle)", 2100], "none", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],

	//Sniper
	["Mk11",30, ["RH_Mk11","MK-11 Rifle (Sniper)", 4550], "none", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
    ["m110sd",30, ["RH_m110sd","M110 Suppressed (Sniper)", 24099], "none", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
    //Shotgun
    ["m110sd",30, ["RH_m110sd","M110 Suppressed (Sniper)", 24099], "none", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
	//Pistol prpl_benelli_14_rail
	["prpl_benelli_pgs",10,["prpl_benelli_pgs","Benelli Super 90 PGS",7000], "rifle","nouse.sqf",["WEAP"],0,"ico_default.paa"],
	["prpl_benelli_14_rail",10,["prpl_benelli_14_rail","Benelli Super 90 Rail",7400], "rifle","nouse.sqf",["WEAP"],0,"ico_default.paa"],

	["cz75",10, ["RH_cz75","CZ-75 (Pistol)", 379], "pistol", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
	["sw659",10, ["RH_sw659","Hush Puppy (Pistol)", 325], "pistol", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
	["mak",10, ["RH_mak","Makarov (Pistol)", 270], "pistol", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
	["m1911",10, ["RH_m1911","M1911 (Pistol)", 749], "pistol", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
	["kimber",10, ["RH_kimber","Kimber (Pistol)", 1349], "pistol", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
	["kimber_nw",10, ["RH_kimber_nw","Lightweight-Kimber (Pistol)", 1349], "pistol", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
	["m9",10, ["RH_m9","M9 (Pistol)", 599], "pistol", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
	["m9c",10, ["RH_m9c","M9 Camo", 599], "pistol", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
	["vz61",10, ["RH_vz61","Škorpion (Pistol)", 600], "pistol", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
	["tt33",10, ["RH_tt33","TT-33 (Pistol)", 350], "pistol", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
	["mk2",10, ["RH_mk2","Ruger Mk II (Pistol) ", 400], "pistol", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
	["p226",10, ["RH_p226","Sig Sauer (Pistol)", 899], "pistol", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
	["p226s",10, ["RH_p226s","Sig Sauer Silver (Pistol)", 1000], "pistol", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
	["vp70",10, ["RH_vp70","Hk VP70 (Pistol)", 800], "pistol", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
	["mateba",10, ["RH_mateba","Mateba Autorevolver (Pistol)", 1298], "pistol", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
	["python",10, ["RH_python","Python (Pistol)", 3289], "pistol", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
	["mp412",10, ["RH_mp412","MP412 REX (Pistol)", 3200], "pistol", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
	["bull",10, ["RH_bull","Taurus Raging Bull (Pistol)", 650], "pistol", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
	["bullb",10, ["RH_bullb","Taurus Raging Bull Black (Pistol)", 650], "pistol", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
	["ttracker",10, ["RH_ttracker","Taurus Model 992 (Pistol)", 430], "pistol", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
	["ttracker_g",10, ["RH_ttracker_g","Taurus Model 992 Gold (Pistol)", 600], "pistol", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
	["fnp45",10, ["RH_fnp45","FN FNP 45 (Pistol)", 630], "pistol", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
	["fnp45t",10, ["RH_fnp45t","FN FNP 45 Tan (Pistol)", 630], "pistol", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
	["fn57",10, ["RH_fn57","FN Five-seven (Pistol)", 1150], "pistol", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
	["fn57_g",10, ["RH_fn57_g","FN Five-seven Green (Pistol)", 1150], "pistol", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
	["fn57_t",10, ["RH_fn57_t","FN Five-seven Tan (Pistol)", 1150], "pistol", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
	["gsh18",10, ["RH_gsh18","GSh-18 (Pistol)", 549], "pistol", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
	["tec9",10, ["RH_tec9","Tec-9 (Pistol)", 215], "pistol", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
	["muzi",10, ["RH_muzi","Mini-Uzi (Pistol)", 1129], "pistol", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
	["deagle",10, ["RH_deagle","Deagle (Pistol)", 1549], "pistol", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
	["deagleg",10, ["RH_deagleg","Deagle Gold (Pistol)", 2000], "pistol", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
	["deagles",10, ["RH_deagles","Deagle Silver (Pistol)", 1800], "pistol", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
	["deaglem",10, ["RH_deaglem","Deagle Muzzle (Pistol)", 1700], "pistol", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
	["Taser_26",10, ["Taser_26","Yellow Taser (Pistol)", 53], "pistol", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],
	["usp",10, ["RH_usp","USP (Pistol)", 1000], "pistol", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],

	//Magazine 
	["prpl_6Rnd_12Gauge_Slug",5, ["prpl_6Rnd_12Gauge_Slug","8 Round 12 Ga. Slugs", 25], "none", "nouse.sqf", ["MAG"],0,"ico_default.paa"],
	["RH_17Rnd_9x19_g17",5, ["RH_17Rnd_9x19_g17","17 Round Glock Magazine", 25], "none", "nouse.sqf", ["MAG"],0,"ico_default.paa"],
	["29rnd_300BLK_STANAG_T",5, ["29rnd_300BLK_STANAG_T","30rnd. .300BLK STANAG", 25], "none", "nouse.sqf", ["MAG"],0,"ico_default.paa"],
	["16Rnd_9x19_cz",5, ["RH_16Rnd_9x19_cz","16Rnd Mag CZ-75", 15], "none", "nouse.sqf", ["MAG"],0,"ico_default.paa"],
	["14Rnd_9x19_sw",5, ["RH_14Rnd_9x19_sw","14Rnd Mag Hush Puppy", 14], "none", "nouse.sqf", ["MAG"],0,"ico_default.paa"],
	["8Rnd_9x18_Mak",5, ["RH_8Rnd_9x18_Mak","8Rnd Mag Makarov", 10], "none", "nouse.sqf", ["MAG"],0,"ico_default.paa"],
	["7Rnd_45cal_m1911",5, ["RH_7Rnd_45cal_m1911","7Rnd Mag M1911/Kimber", 20], "none", "nouse.sqf", ["MAG"],0,"ico_default.paa"],
	["15Rnd_9x19_M9",5, ["RH_15Rnd_9x19_M9","15Rnd Mag M9", 15], "none", "nouse.sqf", ["MAG"],0,"ico_default.paa"],
	["20Rnd_32cal_vz61",5, ["RH_20Rnd_32cal_vz61","20Rnd Mag Škorpion", 15], "none", "nouse.sqf", ["MAG"],0,"ico_default.paa"],
	["8Rnd_762_tt33",5, ["RH_8Rnd_762_tt33","8Rnd Mag TT-33", 15], "none", "nouse.sqf", ["MAG"],0,"ico_default.paa"],
	["10Rnd_22LR_mk2",5, ["RH_10Rnd_22LR_mk2","10Rnd Mag Mk II", 15], "none", "nouse.sqf", ["MAG"],0,"ico_default.paa"],
	["15Rnd_9x19_SIG",5, ["RH_15Rnd_9x19_SIG","15Rnd Mag Sig", 17], "none", "nouse.sqf", ["MAG"],0,"ico_default.paa"],
	["18Rnd_9x19_VP",5, ["RH_18Rnd_9x19_VP","18Rnd Mag VP70", 15], "none", "nouse.sqf", ["MAG"],0,"ico_default.paa"],
    ["6Rnd_44_Mag",5, ["RH_6Rnd_44_Mag","6Rnd Mag Mateba", 10], "none", "nouse.sqf", ["MAG"],0,"ico_default.paa"],
    ["6Rnd_357_Mag",5, ["RH_6Rnd_357_Mag","6Rnd Mag MP412/Python", 20], "none", "nouse.sqf", ["MAG"],0,"ico_default.paa"],
    ["6Rnd_454_Mag",5, ["RH_6Rnd_454_Mag","6Rnd Mag Bull", 20], "none", "nouse.sqf", ["MAG"],0,"ico_default.paa"],
	["6Rnd_45ACP_Mag",5, ["RH_6Rnd_45ACP_Mag","6Rnd Mag Taurus 992", 20], "none", "nouse.sqf", ["MAG"],0,"ico_default.paa"],
	["15Rnd_45cal_fnp",5, ["RH_15Rnd_45cal_fnp","15Rnd Mag FN FNP", 20], "none", "nouse.sqf", ["MAG"],0,"ico_default.paa"],
	["20Rnd_57x28_FN",5, ["RH_20Rnd_57x28_FN","20Rnd Mag Five-seven", 20], "none", "nouse.sqf", ["MAG"],0,"ico_default.paa"],
	["18Rnd_9x19_gsh",5, ["RH_18Rnd_9x19_gsh","18Rnd Mag GSh-18", 15], "none", "nouse.sqf", ["MAG"],0,"ico_default.paa"],
	["32Rnd_9x19_tec",5, ["RH_32Rnd_9x19_tec","32Rnd Mag Tec-9", 15], "none", "nouse.sqf", ["MAG"],0,"ico_default.paa"],
	["30Rnd_9x19_UZI",5, ["RH_30Rnd_9x19_UZI","30Rnd UZI", 25], "none", "nouse.sqf", ["MAG"],0,"ico_default.paa"],
	["7Rnd_50_AE",5, ["RH_7Rnd_50_AE","7Rnd Mag Deagle", 28], "none", "nouse.sqf", ["MAG"],0,"ico_default.paa"],
	["30Rnd_545x39_B_AK",5, ["hlc_30Rnd_545x39_B_AK","30Rnd Mag AKS", 30], "none", "nouse.sqf", ["MAG"],0,"ico_default.paa"],
	["30Rnd_762x39_b_ak",5, ["hlc_30Rnd_762x39_b_ak","30Rnd Mag AKM", 30], "none", "nouse.sqf", ["MAG"],0,"ico_default.paa"],
	["20Rnd_762x51_B_fal",5, ["hlc_20Rnd_762x51_B_fal","20Rnd Mag FN-FAL", 25], "none", "nouse.sqf", ["MAG"],0,"ico_default.paa"],
	["20Rnd_762x51_B_G3",5, ["hlc_20Rnd_762x51_B_G3","20Rnd Mag G3A3", 25], "none", "nouse.sqf", ["MAG"],0,"ico_default.paa"],
	["20Rnd_762x51_B_M14",5, ["hlc_20Rnd_762x51_B_M14","20Rnd Mag M14", 25], "none", "nouse.sqf", ["MAG"],0,"ico_default.paa"],
	["20Rnd_762x51_AR10",5, ["RH_20Rnd_762x51_AR10","20Rnd AR10", 30], "none", "nouse.sqf", ["MAG"],0,"ico_default.paa"],
	["17Rnd_9x19_g17",5, ["RH_17Rnd_9x19_g17","17Rnd Mag G-17", 20], "none", "nouse.sqf", ["MAG"],0,"ico_default.paa"],
	["33Rnd_9x19_g18",5, ["RH_33Rnd_9x19_g18","33Rnd Mag G-18", 20], "none", "nouse.sqf", ["MAG"],0,"ico_default.paa"],
	["30Rnd_556x45_Stanag",5, ["30Rnd_556x45_Stanag","30Rnd Mag Stanag", 25], "none", "nouse.sqf", ["MAG"],0,"ico_default.paa"],
	["26_cartridge",5, ["26_cartridge","Taser Round", 15], "none", "nouse.sqf", ["MAG"],0,"ico_default.paa"],
	["prpl_6Rnd_12Gauge_Slug",5, ["prpl_6Rnd_12Gauge_Slug","Taser Slugs", 20], "none", "nouse.sqf", ["MAG"],0,"ico_default.paa"],
	["12Rnd_45cal_usp",5, ["RH_12Rnd_45cal_usp","12Rnd Mag USP", 20], "none", "nouse.sqf", ["MAG"],0,"ico_default.paa"],
	["30Rnd_9x19_B_MP5",5, ["hlc_30Rnd_9x19_B_MP5","30Rnd Mag MP5", 15], "none", "nouse.sqf", ["MAG"],0,"ico_default.paa"],
	["30Rnd_68x43_FMJ",5, ["RH_30Rnd_68x43_FMJ","30Rnd Mag FMJ", 25], "none", "nouse.sqf", ["MAG"],0,"ico_default.paa"],
	["20Rnd_762x51_M80A1",5, ["RH_20Rnd_762x51_M80A1","20Rnd Mag M80A1", 35], "none", "nouse.sqf", ["MAG"],0,"ico_default.paa"],
	["30Rnd_556x45_B_AUG",5, ["hlc_30Rnd_556x45_B_AUG","30Rnd Mag AUG", 30], "none", "nouse.sqf", ["MAG"],0,"ico_default.paa"],
	["FlareWhite_M32_mag",5, ["FlareWhite_M32_mag","M32 White Flare", 25], "none", "nouse.sqf", ["MAG"],0,"ico_default.paa"],
	["Smoke_M32_mag",5, ["Smoke_M32_mag","M32 Smoke", 25], "none", "nouse.sqf", ["MAG"],0,"ico_default.paa"],

	//Launchers
	["M32_EP1",40, ["M32_EP1","M32 Luancher", 15000], "none", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],

	//Shotguns
	["prpl_benelli_pgs_rail",10, ["prpl_benelli_pgs_rail","Slug Shotgun", 1800], "none", "nouse.sqf", ["WEAP"],0,"ico_default.paa"],

	//Attachments
	["optic_Aco",0, ["optic_Aco","ACO Scope", 150], "none", "nouse.sqf", ["ATTACH"],0,"ico_default.paa"],
	["eotech553",0, ["RH_eotech553","Eo-Tech (Attachment)", 375], "none", "nouse.sqf", ["ATTACH"],0,"ico_default.paa"],
	["compm4s",0, ["RH_compm4s","Aimpoint (Attachment)", 400], "none", "nouse.sqf", ["ATTACH"],0,"ico_default.paa"],
	["compM2l",0, ["RH_compM2l","M2L (Attachment)", 350], "none", "nouse.sqf", ["ATTACH"],0,"ico_default.paa"],
	["shortdot",0, ["RH_shortdot","Shortdot (Attachment)", 375], "none", "nouse.sqf", ["ATTACH"],0,"ico_default.paa"],
	["peq15b",0, ["RH_peq15b","AR Eo-Tech (Attachment)", 375], "none", "nouse.sqf", ["ATTACH"],0,"ico_default.paa"],
	["SFM952V",0, ["RH_SFM952V","Weapon Light (Attachment)", 70], "none", "nouse.sqf", ["ATTACH"],0,"ico_default.paa"],

	//Suit Clothing
	["U_alr_Priest",0, ["U_alr_Priest","ALR_Priest (Clothing)", 300], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["U_alr_Suit",0, ["U_alr_Suit","ALR_SuitA (Clothing)", 279], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["U_alr_SuitB",0, ["U_alr_SuitB","ALR_SuitB (Clothing)", 279], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["U_alr_Suit_1",0, ["U_alr_Suit_1","ALR SuitC (Clothing)", 279], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["U_alr_Suit_2",0, ["U_alr_Suit_2","ALR SuitD (Clothing)", 279], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["U_alr_Suit_4",0, ["U_alr_Suit_4","ALR SuitE (Clothing)", 279], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["U_alr_Suit_5",0, ["U_alr_Suit_5","ALR SuitF (Clothing)", 279], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["U_alr_Suit_6",0, ["U_alr_Suit_6","ALR SuitG (Clothing)", 279], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["U_alr_Suit_7",0, ["U_alr_Suit_7","ALR SuitH (Clothing)", 279], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["U_alr_Suit_8",0, ["U_alr_Suit_8","ALR SuitI (Clothing)", 279], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["U_alr_Suit_9",0, ["U_alr_Suit_9","ALR SuitJ (Clothing)", 279], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["U_alr_Suit_10",0, ["U_alr_Suit_10","ALR SuitK (Clothing)", 279], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["U_alr_Suit_11",0, ["U_alr_Suit_11","ALR SuitL (Clothing)", 279], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],

	//Polo Clothing
	["jamie_armaliferpg",0, ["jamie_armaliferpg","ArmaLiferpg Polo (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["U_C_Journalist",0, ["U_C_Journalist","Journalist (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_polored",0, ["jamie_polored","Polo Red (Clothing)",55], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_poloredjeans",0, ["jamie_poloredjeans","Polo Red Jeans (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_poloredblack",0, ["jamie_poloredblack","Polo Red Black (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_poloorange",0, ["jamie_poloorange","Polo Orange (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],70],
	["jamie_poloorangejeans",0, ["jamie_poloorangejeans","Polo Orange Jeans (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_poloorangeblack",0, ["jamie_poloorangeblack","Polo Orange Black (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_poloyellow",0, ["jamie_poloyellow","Polo Yellow (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_poloyellowjeans",0, ["jamie_poloyellowjeans","Polo Yellow Jeans (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_poloyellowblack",0, ["jamie_poloyellowblack","Polo Yellow Black (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_pololightgreen",0, ["jamie_pololightgreen","Polo Light Green (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_pololightgreenjeans",0, ["jamie_pololightgreenjeans","Polo Light Green Jeans (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_pololightgreenblack",0, ["jamie_pololightgreenblack","Polo Light Green Black (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_pologreen",0, ["jamie_pologreen","Polo Green (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],70],
	["jamie_pologreenjeans",0, ["jamie_pologreenjeans","Polo Green Jeans (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_pologreenblack",0, ["jamie_pologreenblack","Polo Green Black (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_pololightblue",0, ["jamie_pololightblue","Polo Light Blue (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],70],
	["jamie_pololightbluejeans",0, ["jamie_pololightbluejeans","Polo Light Blue Jeans (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_pololightblueblack",0, ["jamie_pololightblueblack","Polo Light Blue Black (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_poloblue",0, ["jamie_poloblue","Polo Blue (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],70],
	["jamie_polobluejeans",0, ["jamie_polobluejeans","Polo Blue Jeans (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_poloblueblack",0, ["jamie_poloblueblack","Polo Blue Black (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_polopurple",0, ["jamie_polopurple","Polo Purple (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],70],
	["jamie_polopurplejeans",0, ["jamie_polopurplejeans","Polo Purple Jeans (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_polopurpleblack",0, ["jamie_polopurpleblack","Polo Purple Black(Clothing)", 50], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_polobrown",0, ["jamie_polobrown","Polo Brown (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_polobrownjeans",0, ["jamie_polobrownjeans","Polo Brown Jeans (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_polobrownblack",0, ["jamie_polobrownblack","Polo Brown Black (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_pologrey",0, ["jamie_pologrey","Polo Grey (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_pologreyjeans",0, ["jamie_pologreyjeans","Polo Grey Jeans (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_pologreyblack",0, ["jamie_pologreyblack","Polo Grey Black (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_polowhite",0, ["jamie_polowhite","Polo White (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_polowhitejeans",0, ["jamie_polowhitejeans","Polo White Jeans (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_polowhiteblack",0, ["jamie_polowhiteblack","Polo White Black (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_poloblack",0, ["jamie_poloblack","Polo Black (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_poloblackjeans",0, ["jamie_poloblackjeans","Polo Black Jeans (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_poloblackblack",0, ["jamie_poloblackblack","Polo Black (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_polocookiemonster",0, ["jamie_polocookiemonster","Polo Cookie Monster (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_polohellokitty",0, ["jamie_polohellokitty","Polo Hello Kitty (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_polohellokitty1",0, ["jamie_polohellokitty1","Polo Hello Kitty 2 (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_polospongebob",0, ["jamie_polospongebob","Polo Spongebob (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_polopatrickstar",0, ["jamie_polopatrickstar","Polo Trickster (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_polodino",0, ["jamie_polodino","Polo Dino (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_polomoon",0, ["jamie_polomoon","Polo Moon (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_poloapple",0, ["jamie_poloapple","Polo Apple (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_polosecurity",0, ["jamie_polosecurity","Polo Security (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_poloqantas",0, ["jamie_poloqantas","Polo Qantas (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_poloaustralia",0, ["jamie_poloaustralia","Polo Australia (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_polocanda",0, ["jamie_polocanda","Polo Canada (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_poloamerica",0, ["jamie_poloamerica","Polo America (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_polofuck",0, ["jamie_polofuck","Polo Fuck (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_pololove",0, ["jamie_pololove","Polo Love (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_polococacola",0, ["jamie_polococacola","Polo Coca-Cola (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_poloface",0, ["jamie_poloface","Polo Face (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_polomrbong",0, ["jamie_polomrbong","Polo MrBong (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
    ["jamie_polostunt",0, ["jamie_polostunt","Polo Stunt (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
    ["jamie_poloangelo",0, ["jamie_poloangelo","Polo Angelo (Clothing)", 50], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],

    //Logo Clothing
	["jamie_doge",0, ["jamie_doge","Doge (Clothing)", 35], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_illuminati",0, ["jamie_illuminati","Illuminati (Clothing)", 35], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_kappa",0, ["jamie_kappa","Kappa (Clothing)", 35], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_jeff",0, ["jamie_jeff","Jeff (Clothing)", 35], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_mexicantroll",0, ["jamie_mexicantroll","Mexican Troll (Clothing)", 35], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_fuckit",0, ["jamie_fuckit","Fuck it (Clothing)", 35], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_drunk",0, ["jamie_drunk","Drunk (Clothing)", 35], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_married",0, ["jamie_married","Married (Clothing)", 35], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_avengers",0, ["jamie_avengers","Avengers (Clothing)", 35], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_shield",0, ["jamie_shield","Shield (Clothing)", 35], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_marvel",0, ["jamie_marvel","Marvel (Clothing)", 35], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_minion",0, ["jamie_minion","Minion (Clothing)", 35], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_monstercat",0, ["jamie_monstercat","Monstercat (Clothing)", 35], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_nike",0, ["jamie_nike","Nike (Clothing)", 35], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_Adidas",0, ["jamie_Adidas","Adidas (Clothing)", 35], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_pancake",0, ["jamie_pancake","Pancake (Clothing)", 35], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_smile",0, ["jamie_smile","Smile (Clothing)", 35], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_tux",0, ["jamie_tux","Tux (Clothing)", 35], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_yaoming",0, ["jamie_yaoming","Yaoming (Clothing)", 35], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_Snoopy",0, ["jamie_Snoopy","Snoopy (Clothing)", 35], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_Coco",0, ["jamie_Coco","Coco (Clothing)", 35], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_Ciggy",0, ["jamie_Ciggy","Ciggy (Clothing)", 35], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_twitch",0, ["jamie_twitch","Twitch (Clothing)", 35], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_polopsisyndicate",0, ["jamie_polopsisyndicate","Polo PsiSyndicate (Clothing)", 35], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_timmac",0, ["jamie_timmac","TimMac (Clothing)", 35], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_ReclaimJoey",0, ["jamie_ReclaimJoey","Reclaim Joey (Clothing)", 35], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_Feature",0, ["jamie_Feature","Feature (Clothing)", 35], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["jamie_Butts",0, ["jamie_Butts","Butts (Clothing)", 35], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],

	//PMC Clothing
	["U_PMC_GTShirt_DJeans",0, ["U_PMC_GTShirt_DJeans","GTShirt_DJeans", 70], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["U_PMC_GTShirt_SJeans",0, ["U_PMC_GTShirt_SJeans","GTShirt_SJeans", 70], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["U_PMC_BlkTShirt_DJeans",0, ["U_PMC_BlkTShirt_DJeans","BlkTShirt_DJeans", 70], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["U_PMC_BlkTShirt_SJeans",0, ["U_PMC_BlkTShirt_SJeans","BlkTShirt_SJeans", 70], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["U_PMC_BluTShirt_SJeans",0, ["U_PMC_BluTShirt_SJeans","BluTShirt_SJeans", 70], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["U_PMC_WTShirt_DJeans",0, ["U_PMC_WTShirt_DJeans","WTShirt_DJeans", 70], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["U_PMC_BluePlaidShirt_BeigeCords",0, ["U_PMC_BluePlaidShirt_BeigeCords","BluePlaidShirt_BeigeCords", 70], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["U_PMC_RedPlaidShirt_DenimCords",0, ["U_PMC_RedPlaidShirt_DenimCords","RedPlaidShirt_DenimCords", 70], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["U_PMC_BlackPoloShirt_BeigeCords",0, ["U_PMC_BlackPoloShirt_BeigeCords","BlackPoloShirt_BeigeCords", 70], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["U_PMC_BluPolo_BgPants",0, ["U_PMC_BluPolo_BgPants","BluPolo_BgPants", 70], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["U_PMC_BgPolo_GrnPants",0, ["U_PMC_BgPolo_GrnPants","BgPolo_GrnPants", 70], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["U_PMC_BlckPolo_BgPants",0, ["U_PMC_BlckPolo_BgPants","BlckPolo_BgPants", 70], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["U_PMC_BlckPolo_BluPants",0, ["U_PMC_BlckPolo_BluPants","BlckPolo_BluPants", 70], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["U_PMC_BluPolo_GrnPants",0, ["U_PMC_BluPolo_GrnPants","BluPolo_GrnPants", 70], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["U_PMC_BrnPolo_BgPants",0, ["U_PMC_BrnPolo_BgPants","BrnPolo_BgPants", 70], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["U_PMC_BrnPolo_BluPants",0, ["U_PMC_BrnPolo_BluPants","BrnPolo_BluPants", 70], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["U_PMC_GrnPolo_BgPants",0, ["U_PMC_GrnPolo_BgPants","GrnPolo_BgPants", 70], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["U_PMC_WhtPolo_BgPants",0, ["U_PMC_WhtPolo_BgPants","WhtPolo_BgPants", 70], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["U_PMC_WhtPolo_BluPants",0, ["U_PMC_WhtPolo_BluPants","WhtPolo_BluPants", 70], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],
	["U_PMC_WhtPolo_GrnPants",0, ["U_PMC_WhtPolo_GrnPants","WhtPolo_GrnPants", 70], "none", "nouse.sqf", ["UNIF"],0,"ico_default.paa"],

	//Headgear Clothing
	["H_Cap_press",0, ["H_Cap_press","Cap Press", 15], "none", "nouse.sqf", ["HDGR"],0,"ico_default.paa"],
	["Kio_Afro_Hat",0, ["Kio_Afro_Hat","Afro", 15], "none", "nouse.sqf", ["HDGR"],0,"ico_default.paa"],
	["kio_vfv_mask",0, ["kio_vfv_mask","Anonymous Mask", 25], "none", "nouse.sqf", ["HDGR"],0,"ico_default.paa"],
	["Kio_Capital_Hat",0, ["Kio_Capital_Hat","Capital Hat", 45], "none", "nouse.sqf", ["HDGR"],0,"ico_default.paa"],
	["Kio_No1_Hat",0, ["Kio_No1_Hat","Number 1 Hat", 15], "none", "nouse.sqf", ["HDGR"],0,"ico_default.paa"],
	["Kio_Pirate_Hat",0, ["Kio_Pirate_Hat","Pirate Hat", 15], "none", "nouse.sqf", ["HDGR"],0,"ico_default.paa"],
	["Kio_Hat",0, ["Kio_Hat","Warm Hat", 25], "none", "nouse.sqf", ["HDGR"],0,"ico_default.paa"],
	["Kio_Santa_Hat",0, ["Kio_Santa_Hat","Santa Hat", 35], "none", "nouse.sqf", ["HDGR"],0,"ico_default.paa"],
	["Kio_Spinning_Hat",0, ["Kio_Spinning_Hat","Spinning Hat", 26], "none", "nouse.sqf", ["HDGR"],0,"ico_default.paa"],
	["kio_skl_msk",0, ["kio_skl_msk","White Skull Mask", 15], "none", "nouse.sqf", ["HDGR"],0,"ico_default.paa"],
	["kio_skl_msk_red",0, ["kio_skl_msk_red","Red Skull Mask", 20], "none", "nouse.sqf", ["HDGR"],0,"ico_default.paa"],
	["kio_skl_msk_grn",0, ["kio_skl_msk_grn","Green Skull Mask", 18], "none", "nouse.sqf", ["HDGR"],0,"ico_default.paa"],
	["crg_bunny",0, ["crg_bunny","Bunny Ears", 10], "none", "nouse.sqf", ["HDGR"],0,"ico_default.paa"],
	["crg_zorro",0, ["crg_zorro","Zorro Hat", 25], "none", "nouse.sqf", ["HDGR"],0,"ico_default.paa"],
	["cowboyhat",0, ["cowboyhat","Cowboy Hat", 30], "none", "nouse.sqf", ["HDGR"],0,"ico_default.paa"],
	["H_Bandanna_gry",0, ["H_Bandanna_gry","Black Bandanna", 5], "none", "nouse.sqf", ["HDGR"],0,"ico_default.paa"],
	["H_Bandanna_blu",0, ["H_Bandanna_blu","Blue Bandanna", 5], "none", "nouse.sqf", ["HDGR"],0,"ico_default.paa"],
	["H_Bandanna_cbr",0, ["H_Bandanna_cbr","Coyote Bandanna", 5], "none", "nouse.sqf", ["HDGR"],0,"ico_default.paa"],
	["H_Bandanna_khk",0, ["H_Bandanna_khk","Khaki Bandanna", 5], "none", "nouse.sqf", ["HDGR"],0,"ico_default.paa"],
	["H_Bandanna_mcamo",0, ["H_Bandanna_mcamo","MTP Bandanna", 5], "none", "nouse.sqf", ["HDGR"],0,"ico_default.paa"],
	["H_Bandanna_sgg",0, ["H_Bandanna_sgg","Sage Bandanna", 5], "none", "nouse.sqf", ["HDGR"],0,"ico_default.paa"],
	["H_Bandanna_sand",0, ["H_Bandanna_sand","Sand Bandanna", 5], "none", "nouse.sqf", ["HDGR"],0,"ico_default.paa"],
	["H_Bandanna_camo",0, ["H_Bandanna_camo","Camo Bandanna", 6], "none", "nouse.sqf", ["HDGR"],0,"ico_default.paa"],
	["H_Bandanna_surfer",0, ["H_Bandanna_surfer","Surfer Bandanna", 5], "none", "nouse.sqf", ["HDGR"],0,"ico_default.paa"],
	["H_Bandanna_surfer_blk",0, ["H_Bandanna_surfer_blk","Surfer Black Bandanna", 5], "none", "nouse.sqf", ["HDGR"],0,"ico_default.paa"],
	["H_Bandanna_surfer_grn",0, ["H_Bandanna_surfer_grn","Surfer Green Bandanna", 5], "none", "nouse.sqf", ["HDGR"],0,"ico_default.paa"],
	["H_Bandanna_camo",0, ["H_Bandanna_camo","Woodland Bandanna", 5], "none", "nouse.sqf", ["HDGR"],0,"ico_default.paa"],
	["H_Booniehat_khk",0, ["H_Booniehat_khk","Khaki Booniehat", 15], "none", "nouse.sqf", ["HDGR"],0,"ico_default.paa"],
	["H_Booniehat_mcamo",0, ["H_Booniehat_mcamo","MTP Booniehat", 15], "none", "nouse.sqf", ["HDGR"],0,"ico_default.paa"],
	["H_Booniehat_oli",0, ["H_Booniehat_oli","Olive Booniehat", 20], "none", "nouse.sqf", ["HDGR"],0,"ico_default.paa"],
	["H_Booniehat_tan",0, ["H_Booniehat_tan","Sand Booniehat", 20], "none", "nouse.sqf", ["HDGR"],0,"ico_default.paa"],
	["H_Booniehat_dgtl",0, ["H_Booniehat_dgtl","AAF Booniehat", 15], "none", "nouse.sqf", ["HDGR"],0,"ico_default.paa"],
	["H_StrawHat",0, ["H_StrawHat","Straw Hat", 5], "none", "nouse.sqf", ["HDGR"],0,"ico_default.paa"],
	["H_StrawHat_dark",0, ["H_StrawHat_dark","Straw Hat (Dark)", 10], "none", "nouse.sqf", ["HDGR"],0,"ico_default.paa"],
	["H_Hat_blue",0, ["H_Hat_blue","Hat blue", 15], "none", "nouse.sqf", ["HDGR"],0,"ico_default.paa"],
	["H_Hat_brown",0, ["H_Hat_brown","Hat brown", 15], "none", "nouse.sqf", ["HDGR"],0,"ico_default.paa"],
	["H_Hat_checker",0, ["H_Hat_checker","Hat checker", 15], "none", "nouse.sqf", ["HDGR"],0,"ico_default.paa"],
	["H_Hat_grey",0, ["H_Hat_grey","Hat grey", 15], "none", "nouse.sqf", ["HDGR"],0,"ico_default.paa"],
	["H_Hat_tan",0, ["H_Hat_tan","Hat tan", 15], "none", "nouse.sqf", ["HDGR"],0,"ico_default.paa"],
	["H_Cap_blk",0, ["H_Cap_blk","Cap black", 15], "none", "nouse.sqf", ["HDGR"],0,"ico_default.paa"],
	["H_Cap_blu",0, ["H_Cap_blu","Cap blue", 15], "none", "nouse.sqf", ["HDGR"],0,"ico_default.paa"],
	["H_Cap_grn",0, ["H_Cap_grn","Cap green", 15], "none", "nouse.sqf", ["HDGR"],0,"ico_default.paa"],
	["H_Cap_grn_BI",0, ["H_Cap_grn_BI","Cap green BI", 20], "none", "nouse.sqf", ["HDGR"],0,"ico_default.paa"],
	["H_Cap_oli",0, ["H_Cap_oli","Cap olive", 15], "none", "nouse.sqf", ["HDGR"],0,"ico_default.paa"],
	["H_Cap_red",0, ["H_Cap_red","Cap red", 15], "none", "nouse.sqf", ["HDGR"],0,"ico_default.paa"],
	["H_Cap_surfer",0, ["H_Cap_surfer","Cap surfer", 15], "none", "nouse.sqf", ["HDGR"],0,"ico_default.paa"],
	["H_Cap_tan",0, ["H_Cap_tan","Cap tan", 15], "none", "nouse.sqf", ["HDGR"],0,"ico_default.paa"],

	//FaceWear Clothing
	["EWK_Cig1",0, ["EWK_Cig1","EWK_Cig1", 5], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],
	["EWK_Cig2",0, ["EWK_Cig2","EWK_Cig2", 5], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],
	["EWK_Cig3",0, ["EWK_Cig3","EWK_Cig3", 5], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],
	["EWK_Cig4",0, ["EWK_Cig4","EWK_Cig4", 5], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],
	["EWK_Glasses_Cig1",0, ["EWK_Glasses_Cig1","EWK_Glasses_Cig1", 15], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],
	["EWK_Glasses_Cig2",0, ["EWK_Glasses_Cig2","EWK_Glasses_Cig2", 15], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],
	["EWK_Glasses_Cig3",0, ["EWK_Glasses_Cig3","EWK_Glasses_Cig3", 15], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],
	["EWK_Glasses_Cig4",0, ["EWK_Glasses_Cig4","EWK_Glasses_Cig4", 15], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],
	["EWK_Cigar1",0, ["EWK_Cigar1","EWK_Cigar1", 15], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],
	["EWK_Cigar2",0, ["EWK_Cigar2","EWK_Cigar2", 15], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],
	["EWK_Glasses_Shemag_GRE_Cig6",0, ["EWK_Glasses_Shemag_GRE_Cig6","EWK_Glasses_Shemag_GRE_Cig6", 20], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],
	["EWK_Glasses_Shemag_NB_Cig6",0, ["EWK_Glasses_Shemag_NB_Cig6","EWK_Glasses_Shemag_NB_Cig6", 20], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],
	["EWK_Glasses_Shemag_tan_Cig6",0, ["EWK_Glasses_Shemag_tan_Cig6","EWK_Glasses_Shemag_tan_Cig6", 20], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],
	["EWK_Shemag_LULZ",0, ["EWK_Shemag_LULZ","EWK_Shemag_LULZ", 20], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],
	["EWK_Shemag_GRE",0, ["EWK_Shemag_GRE","EWK_Shemag_GRE", 20], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],
	["EWK_Shemag_tan",0, ["EWK_Shemag_tan","EWK_Shemag_tan", 20], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],
	["EWK_Shemag_NB",0, ["EWK_Shemag_NB","EWK_Shemag_NB", 20], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],
	["SFG_Tac_smallBeardB",0, ["SFG_Tac_smallBeardB","SFG_Tac_smallBeardB", 15], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],
	["SFG_Tac_smallBeardD",0, ["SFG_Tac_smallBeardD","SFG_Tac_smallBeardD", 15], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],
	["SFG_Tac_smallBeardG",0, ["SFG_Tac_smallBeardG","SFG_Tac_smallBeardG", 15], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],
	["SFG_Tac_smallBeardO",0, ["SFG_Tac_smallBeardO","SFG_Tac_smallBeardO", 15], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],
	["SFG_Tac_BeardB",0, ["SFG_Tac_BeardB","SFG_Tac_BeardB", 15], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],
	["SFG_Tac_BeardD",0, ["SFG_Tac_BeardD","SFG_Tac_BeardD", 15], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],
	["SFG_Tac_BeardG",0, ["SFG_Tac_BeardG","SFG_Tac_BeardG", 15], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],
	["SFG_Tac_BeardO",0, ["SFG_Tac_BeardO","SFG_Tac_BeardO", 15], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],
	["SFG_Tac_chinlessbB",0, ["SFG_Tac_chinlessbB","SFG_Tac_chinlessbB", 15], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],
	["SFG_Tac_chinlessbD",0, ["SFG_Tac_chinlessbD","SFG_Tac_chinlessbD", 15], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],
	["SFG_Tac_chinlessbG",0, ["SFG_Tac_chinlessbG","SFG_Tac_chinlessbG", 15], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],
	["SFG_Tac_chinlessbO",0, ["SFG_Tac_chinlessbO","SFG_Tac_chinlessbO", 15], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],
	["SFG_Tac_moustacheB",0, ["SFG_Tac_moustacheB","SFG_Tac_moustacheB", 15], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],
	["SFG_Tac_moustacheD",0, ["SFG_Tac_moustacheD","SFG_Tac_moustacheD", 15], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],
	["SFG_Tac_moustacheG",0, ["SFG_Tac_moustacheG","SFG_Tac_moustacheG", 15], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],
	["SFG_Tac_moustacheO",0, ["SFG_Tac_moustacheO","SFG_Tac_moustacheO", 15], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],
	["SFG_Tac_ChopsB",0, ["SFG_Tac_ChopsB","SFG_Tac_ChopsB", 20], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],
	["SFG_Tac_ChopsD",0, ["SFG_Tac_ChopsD","SFG_Tac_ChopsD", 20], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],
	["SFG_Tac_ChopsG",0, ["SFG_Tac_ChopsG","SFG_Tac_ChopsG", 20], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],
	["SFG_Tac_ChopsO",0, ["SFG_Tac_ChopsO","SFG_Tac_ChopsO", 20], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],
	["G_Shades_Black",0, ["G_Shades_Black","G_Shades_Black", 20], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],
	["G_Shades_Blue",0, ["G_Shades_Blue","G_Shades_Blue", 15], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],
	["G_Shades_Green",0, ["G_Shades_Green","G_Shades_Green", 15], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],
	["G_Shades_Red",0, ["G_Shades_Red","G_Shades_Red", 15], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],
	["G_Sport_Red",0, ["G_Sport_Red","G_Sport_Red", 15], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],
	["G_Sport_Blackyellow",0, ["G_Sport_Blackyellow","G_Sport_Blackyellow", 15], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],
	["G_Sport_Checkered",0, ["G_Sport_Checkered","G_Sport_Checkered", 15], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],
	["G_Sport_Blackred",0, ["G_Sport_Blackred","G_Sport_Blackred", 15], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],
	["G_Sport_BlackWhite",0, ["G_Sport_BlackWhite","G_Sport_BlackWhite", 15], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],
	["G_Sport_Greenblack",0, ["G_Sport_Greenblack","G_Sport_Greenblack", 15], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],
	["G_Squares",0, ["G_Squares","G_Squares", 15], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],
	["G_Spectacles",0, ["G_Spectacles","G_Spectacles", 20], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],
	["G_Spectacles_Tinted",0, ["G_Spectacles_Tinted","G_Spectacles_Tinted", 15], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],
	["G_Aviator",0, ["G_Aviator","G_Aviator", 20], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],
	["G_Lady_Mirror",0, ["G_Lady_Mirror","G_Lady_Mirror", 25], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],
	["G_Lady_Dark",0, ["G_Lady_Dark","G_Lady_Dark", 15], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],
	["G_Lady_Blue",0, ["G_Lady_Blue","G_Lady_Blue", 15], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],
	["G_Lowprofile",0, ["G_Lowprofile","G_Lowprofile", 20], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],
	["G_Combat",0, ["G_Combat","G_Combat", 20], "none", "nouse.sqf", ["GOGLE"],0,"ico_default.paa"],

	//Vests Clothing
	["V_Press_F",0, ["V_Press_F","Blue Press Vest", 150], "none", "nouse.sqf", ["VEST"],0,"ico_default.paa"],
	["V_BandollierB_khk",0, ["V_BandollierB_khk","Khaki Bandollier", 60], "none", "nouse.sqf", ["VEST"],0,"ico_default.paa"],
	["V_BandollierB_cbr",0, ["V_BandollierB_cbr","CBR Bandollier", 60], "none", "nouse.sqf", ["VEST"],0,"ico_default.paa"],
	["V_BandollierB_rgr",0, ["V_BandollierB_rgr","RGR Bandollier", 60], "none", "nouse.sqf", ["VEST"],0,"ico_default.paa"],
	["V_BandollierB_blk",0, ["V_BandollierB_blk","Black Bandollier", 60], "none", "nouse.sqf", ["VEST"],0,"ico_default.paa"],
	["V_BandollierB_oli",0, ["V_BandollierB_oli","Olive Bandollier", 60], "none", "nouse.sqf", ["VEST"],0,"ico_default.paa"],

	//Backpacks Clothing
	["B_AssaultPack_khk",0, ["B_AssaultPack_khk","Khaki Assault Pack", 25], "none", "nouse.sqf", ["BKPK"],0,"ico_default.paa"],
	["B_AssaultPack_dgtl",0, ["B_AssaultPack_dgtl","Digital Assault Pack", 25], "none", "nouse.sqf", ["BKPK"],0,"ico_default.paa"],
	["B_AssaultPack_rgr",0, ["B_AssaultPack_rgr","RGR Assault Pack", 25], "none", "nouse.sqf", ["BKPK"],0,"ico_default.paa"],
	["B_AssaultPack_sgg",0, ["B_AssaultPack_sgg","SGG Assault Pack", 25], "none", "nouse.sqf", ["BKPK"],0,"ico_default.paa"],
	["B_AssaultPack_blk",0, ["B_AssaultPack_blk","Black Assault Pack", 25], "none", "nouse.sqf", ["BKPK"],0,"ico_default.paa"],
	["B_AssaultPack_cbr",0, ["B_AssaultPack_cbr","CBR Assault Pack", 25], "none", "nouse.sqf", ["BKPK"],0,"ico_default.paa"],
	["B_AssaultPack_mcamo",0, ["B_AssaultPack_mcamo","Multicam Assault Pack", 30], "none", "nouse.sqf", ["BKPK"],0,"ico_default.paa"],
	["B_AssaultPack_ocamo",0, ["B_AssaultPack_ocamo","Camo Assault Pack", 30], "none", "nouse.sqf", ["BKPK"],0,"ico_default.paa"],
	["B_Kitbag_rgr",0, ["B_Kitbag_rgr","RGR Kitbag", 20], "none", "nouse.sqf", ["BKPK"],0,"ico_default.paa"],
	["B_Kitbag_mcamo",0, ["B_Kitbag_mcamo","Multicam Kitbag", 20], "none", "nouse.sqf", ["BKPK"],0,"ico_default.paa"],
	["B_Kitbag_sgg",0, ["B_Kitbag_sgg","SGG Kit Bag", 20], "none", "nouse.sqf", ["BKPK"],0,"ico_default.paa"],
	["B_Kitbag_cbr",0, ["B_Kitbag_cbr","B_Kitbag_cbr", 20], "none", "nouse.sqf", ["BKPK"],0,"ico_default.paa"],
	["B_TacticalPack_rgr",0, ["B_TacticalPack_rgr","B_TacticalPack_rgr", 20], "none", "nouse.sqf", ["BKPK"],0,"ico_default.paa"],
	["B_TacticalPack_mcamo",0, ["B_TacticalPack_mcamo","B_TacticalPack_mcamo", 20], "none", "nouse.sqf", ["BKPK"],0,"ico_default.paa"],
	["B_TacticalPack_ocamo",0, ["B_TacticalPack_ocamo","B_TacticalPack_ocamo", 20], "none", "nouse.sqf", ["BKPK"],0,"ico_default.paa"],
	["B_TacticalPack_blk",0, ["B_TacticalPack_blk","B_TacticalPack_blk", 20], "none", "nouse.sqf", ["BKPK"],0,"ico_default.paa"],
	["B_TacticalPack_oli",0, ["B_TacticalPack_oli","B_TacticalPack_oli", 20], "none", "nouse.sqf", ["BKPK"],0,"ico_default.paa"],
	["B_FieldPack_blk",0, ["B_FieldPack_blk","B_FieldPack_blk", 40], "none", "nouse.sqf", ["BKPK"],0,"ico_default.paa"],
	["B_FieldPack_ocamo",0, ["B_FieldPack_ocamo","B_FieldPack_ocamo", 40], "none", "nouse.sqf", ["BKPK"],0,"ico_default.paa"],
	["B_FieldPack_oucamo",0, ["B_FieldPack_oucamo","B_FieldPack_oucamo", 40], "none", "nouse.sqf", ["BKPK"],0,"ico_default.paa"],
	["B_FieldPack_oucamo",0, ["B_FieldPack_oucamo","B_FieldPack_oucamo", 40], "none", "nouse.sqf", ["BKPK"],0,"ico_default.paa"],
	["B_Bergen_sgg",0, ["B_Bergen_sgg","B_Bergen_sgg", 50], "none", "nouse.sqf", ["BKPK"],0,"ico_default.paa"],
	["B_Bergen_mcamo",0, ["B_Bergen_mcamo","B_Bergen_mcamo", 50], "none", "nouse.sqf", ["BKPK"],0,"ico_default.paa"],
	["B_Bergen_rgr",0, ["B_Bergen_rgr","B_Bergen_rgr", 50], "none", "nouse.sqf", ["BKPK"],0,"ico_default.paa"],
	["B_Bergen_blk",0, ["B_Bergen_blk","B_Bergen_blk", 50], "none", "nouse.sqf", ["BKPK"],0,"ico_default.paa"],
	["B_Kitbag_sgg",0, ["B_Kitbag_sgg","B_Kitbag_sgg", 50], "none", "nouse.sqf", ["BKPK"],0,"ico_default.paa"],
	["B_Kitbag_cbr",0, ["B_Kitbag_cbr","B_Kitbag_cbr", 50], "none", "nouse.sqf", ["BKPK"],0,"ico_default.paa"],
	["B_Carryall_oli",0, ["B_Carryall_oli","B_Carryall_oli", 70], "none", "nouse.sqf", ["BKPK"],0,"ico_default.paa"],
	["B_Carryall_khk",0, ["B_Carryall_khk","B_Carryall_khk", 70], "none", "nouse.sqf", ["BKPK"],0,"ico_default.paa"],
	["B_Carryall_cbr",0, ["B_Carryall_cbr","B_Carryall_cbr", 70], "none", "nouse.sqf", ["BKPK"],0,"ico_default.paa"],
	["B_Carryall_ocamo",0, ["B_Carryall_ocamo","B_Carryall_ocamo", 70], "none", "nouse.sqf", ["BKPK"],0,"ico_default.paa"],
	["B_Carryall_oucamo",0, ["B_Carryall_oucamo","B_Carryall_oucao", 70], "none", "nouse.sqf", ["BKPK"],0,"ico_default.paa"],
	["B_Carryall_mcamo",0, ["B_Carryall_mcamo","Multicam Carryall Backpack", 70], "none", "nouse.sqf", ["BKPK"],0,"ico_default.paa"]

	];